"""initial schema

Revision ID: 3e9bd2201c45
Revises:
Create Date: 2026-06-30 18:27:21.630270
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "3e9bd2201c45"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("office_lat", sa.Float(), nullable=True),
        sa.Column("office_lng", sa.Float(), nullable=True),
        sa.Column("allowed_radius_m", sa.Float(), nullable=False),
        sa.Column("late_cutoff", sa.String(length=5), nullable=False),
        sa.Column("free_late_marks", sa.Integer(), nullable=False),
        sa.Column("working_hours_per_day", sa.Float(), nullable=False),
        sa.Column("working_days_per_month", sa.Integer(), nullable=False),
        sa.Column("holidays", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.String(length=16), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=180), nullable=True),
        sa.Column("department", sa.String(length=60), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("designation", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("monthly_salary", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("hourly_rate", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("fixed_components", sa.JSON(), nullable=False),
        sa.Column("deductions", sa.JSON(), nullable=False),
        sa.Column("wfh_limit", sa.Integer(), nullable=False),
        sa.Column("free_punch", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("pin_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "attendance_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.String(length=16), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("leave_type", sa.String(length=8), nullable=True),
        sa.Column("total_hours", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("paid_hours", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("is_wfh", sa.Boolean(), nullable=False),
        sa.Column("is_field_duty", sa.Boolean(), nullable=False),
        sa.Column("is_late", sa.Boolean(), nullable=False),
        sa.Column("manual_override", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "date", name="uq_attendance_emp_date"),
    )
    op.create_index(op.f("ix_attendance_days_date"), "attendance_days", ["date"], unique=False)
    op.create_index(
        op.f("ix_attendance_days_employee_id"), "attendance_days", ["employee_id"], unique=False
    )
    op.create_table(
        "hourly_rate_overrides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("employee_id", sa.String(length=16), nullable=False),
        sa.Column("hourly_rate", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("month", "employee_id", name="uq_override_month_emp"),
    )
    op.create_index(
        op.f("ix_hourly_rate_overrides_employee_id"),
        "hourly_rate_overrides",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_hourly_rate_overrides_month"), "hourly_rate_overrides", ["month"], unique=False
    )
    op.create_table(
        "leave_balances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.String(length=16), nullable=False),
        sa.Column("leave_type", sa.String(length=8), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "leave_type", name="uq_balance_emp_type"),
    )
    op.create_index(
        op.f("ix_leave_balances_employee_id"), "leave_balances", ["employee_id"], unique=False
    )
    op.create_table(
        "leave_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.String(length=16), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=False),
        sa.Column("leave_type", sa.String(length=8), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("reviewed_by", sa.String(length=16), nullable=True),
        sa.Column("review_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_leave_requests_employee_id"), "leave_requests", ["employee_id"], unique=False
    )
    op.create_index(op.f("ix_leave_requests_status"), "leave_requests", ["status"], unique=False)
    op.create_table(
        "payroll_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("employee_id", sa.String(length=16), nullable=False),
        sa.Column("gross", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("deductions_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("net", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("breakdown", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("month", "employee_id", name="uq_payroll_month_emp"),
    )
    op.create_index(
        op.f("ix_payroll_records_employee_id"), "payroll_records", ["employee_id"], unique=False
    )
    op.create_index(op.f("ix_payroll_records_month"), "payroll_records", ["month"], unique=False)
    op.create_table(
        "attendance_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("day_id", sa.Integer(), nullable=False),
        sa.Column("punch_in", sa.DateTime(timezone=True), nullable=False),
        sa.Column("punch_out", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["day_id"],
            ["attendance_days.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_attendance_sessions_day_id"), "attendance_sessions", ["day_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attendance_sessions_day_id"), table_name="attendance_sessions")
    op.drop_table("attendance_sessions")
    op.drop_index(op.f("ix_payroll_records_month"), table_name="payroll_records")
    op.drop_index(op.f("ix_payroll_records_employee_id"), table_name="payroll_records")
    op.drop_table("payroll_records")
    op.drop_index(op.f("ix_leave_requests_status"), table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_employee_id"), table_name="leave_requests")
    op.drop_table("leave_requests")
    op.drop_index(op.f("ix_leave_balances_employee_id"), table_name="leave_balances")
    op.drop_table("leave_balances")
    op.drop_index(op.f("ix_hourly_rate_overrides_month"), table_name="hourly_rate_overrides")
    op.drop_index(op.f("ix_hourly_rate_overrides_employee_id"), table_name="hourly_rate_overrides")
    op.drop_table("hourly_rate_overrides")
    op.drop_index(op.f("ix_attendance_days_employee_id"), table_name="attendance_days")
    op.drop_index(op.f("ix_attendance_days_date"), table_name="attendance_days")
    op.drop_table("attendance_days")
    op.drop_table("employees")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
